### ISSUE TITLE
Not working with new client

### ISSUE THREAD

**Issue by TheMineA7** [Cadrach/lol_ise#3] opened 2016-12-24 14:51 UTC
### Browser (Chrome, Safari, Internet Explorer) and Version
Chrome
### Steps to reproduce
Make an item set on the website.
Download the new LoL client.
Install as told by the readme
Go into a custom match.
Expect to be able to choose item set, but I can't.

**Comment by Cadrach** [comment] 2016-12-24 17:48
Could you provide a .zip of your Config folder?

Also, are you sure you deployed to the correct folder? It is possible you have multiple installs of League of Legends and are apply the .zip to the wrong folder.

**Comment by Cadrach** [comment] 2017-01-05 12:40
Closing this issue because of lack of information. Please re-open once you can provide your Config folder for me to reproduce.

**Closed by Cadrach** 2017-01-05 12:40 UTC
