### ISSUE TITLE
Missing champions?

### ISSUE THREAD

**Issue by yu39466** [Cadrach/lol_ise#2] opened 2016-12-24 13:04 UTC
With pre-existing builds that include multiple champions, a lot of them are missing

**Comment by Cadrach** [comment] 2016-12-24 17:47
Could you provide a .zip of your Config folder so that I can take a look?

**Comment by Cadrach** [comment] 2016-12-29 21:35
Think this is a duplicate of #9, should be solved with 0.5

**Closed by Cadrach** 2016-12-29 21:35 UTC
