### ISSUE TITLE
Spell vamp items

### ISSUE THREAD

**Issue by WhydidIhavetomakeanaccountforthis** [Cadrach/lol_ise#29] opened 2017-04-17 12:14 UTC
More of a minor oversight than an issue, but Elixir of Wrath is listed as a spell vamp item while Death's Dance isn't.

**Comment by Cadrach** [comment] 2017-04-17 16:56
The item tagging comes from the Riot API data, so not much I can do there without hard-coding something, which I prefer to avoid when not a major issue. Even then, I would have said the error is more on the side of the Elixir than Death's Dance, as both are not using spell vamp but lifesteal based on physical damage dealt.

Closing this since it is not major, and the root of the problem is on Riot side.

**Comment by Cadrach** [comment] 2017-04-17 16:57
Love your username by the way ^_^

**Closed by Cadrach** 2017-04-17 16:56 UTC
