### ISSUE TITLE
Champions Names + Item Icons Bug

### ISSUE THREAD

**Issue by Auzuru** [Cadrach/lol_ise#55] opened 2017-08-21 17:11 UTC
I don't actually know how this forum works. But there's a problem at "lol item set editor" where all names from Heroes are different and a lot of Items have no Icons or different ones, as well as all, builds disappeared from Heroes that names are changed.

![lol](https://user-images.githubusercontent.com/31218570/29530449-1e8f44b8-86a4-11e7-9a41-61b6b152b01b.PNG)

**Comment by chaoticnote** [comment] 2017-08-29 04:55
Can confirm.
![image](https://user-images.githubusercontent.com/28378016/29804979-8434a686-8c3b-11e7-9fb6-8ee93ae4b22b.png)
![image](https://user-images.githubusercontent.com/28378016/29804982-8714b10c-8c3b-11e7-93e7-c1cce3da17ba.png)
Google Chrome Version 60.0.3112.101

**Comment by Cadrach** [comment] 2017-08-29 17:18
I think this is a duplicate of #54, will work on it when I get back from holidays next week!

**Comment by Cadrach** [comment] 2017-09-04 08:37
Back from holidays, and I am unable to reproduce the issue on my side. Can you try clearing your cache and let me know if the problem is still there?

**Comment by Cadrach** [comment] 2017-09-14 09:51
Closing since linked to #54

**Closed as completed by Cadrach** 2017-09-14 09:51 UTC
